import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider"
import { Bleed ,Stack,Box,Flex } from "@chakra-ui/react"
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={"antialiased"}
      >
        <Provider>
          <Box>
          
            <Flex gap="5" justify="center" direction="row" p="5">
              <ul>
              <Stack direction={{ base: "row", md: "row" }} gap="5">
                <li>
                <Link href="/">
                  Home
                </Link>
                </li>
                <li>
                  <Link href="/about">
                  About
                </Link>
                </li>
                <li>
                  <Link href="/message">
                  Message
                </Link>
                </li>
                <li>
                  <Link href="/analysis">
                  Analysis
                </Link>
                </li>
                </Stack>
              </ul>
            </Flex>
          </Box>
          {children}
        </Provider>
      </body>
    </html>
  );
}
